=== RedaBetancor/Biblioteca/BookShop.dtd
<!ELEMENT BookShop (Timetable, w:Workers, c:Clients, Products)>
<!ATTLIST BookShop place CDATA #REQUIRED>
<!ELEMENT Timetable (WorkingD, OpeningH)>
<!ELEMENT WorkingD (#PCDATA)>
<!ELEMENT OpeningH (#PCDATA)>
<!ELEMENT w:Workers (w:Worker)>
<!ATTLIST w:Workers xmlns:w CDATA #REQUIRED>
<!ELEMENT w:Worker (w:Name, w:DNI, w:Age)>
<!ELEMENT w:Name (#PCDATA)> 
<!ELEMENT w:DNI (#PCDATA)>
<!ELEMENT w:Age (#PCDATA)>
<!ELEMENT c:Clients (c:Client*)>
<!ATTLIST c:Clients xmlns:c CDATA #REQUIRED>
<!ELEMENT c:Client (c:Name*, c:DNI*, c:Email*, c:PhoneN*)>
<!ELEMENT c:Name (#PCDATA)>
<!ELEMENT c:DNI (#PCDATA)>  
<!ELEMENT c:Email (#PCDATA)>
<!ELEMENT c:PhoneN (#PCDATA)>
<!ELEMENT Products (Product)>
<!ELEMENT Product (Id, Price, Offer, Quantity)>
<!ELEMENT Id (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT Offer (#PCDATA)>
<!ELEMENT Quantity (#PCDATA)>

=== RedaBetancor/Biblioteca/BookShop.xml
<!DOCTYPE BookShop SYSTEM "BookShop.dtd">

<BookShop place="C/Doctor Juan de Padilla, 19, Las Palmas de Gran Canaria">

    <Timetable>

        <WorkingD>Abrimos de lunes a viernes</WorkingD>
        <OpeningH>Nuestro horario es de 09:00 a 17:30</OpeningH>

    </Timetable>

    <w:Workers xmlns:w="http://www.workers.com/worker">

        <w:Worker>

            <w:Name>Pablo</w:Name>
            <w:DNI>49986748W</w:DNI>
            <w:Age>28</w:Age>

        </w:Worker>

    </w:Workers>

    <c:Clients xmlns:c="https://www.clients.com/client">

        <c:Client>

            <c:Name>David</c:Name>
            <c:DNI>49964739D</c:DNI>
            <c:Email>davidsantidad@gmail.com</c:Email>
            <c:PhoneN>622746385</c:PhoneN>

        </c:Client>

        <c:Client>

            <c:Name>Augusto</c:Name>
            <c:DNI>49983745E</c:DNI>
            <c:Email>augustodelafe@gmail.com</c:Email>
            <c:PhoneN></c:PhoneN>

        </c:Client>

    </c:Clients>

    <Products>

        <Product>

            <Id>B0BXPJ1Z1S</Id>
            <Price>18,00â‚¬</Price>
            <Offer>No</Offer>
            <Quantity>2</Quantity>

        </Product>

    </Products>

</BookShop>
